pipeline {
    agent any
    environment {
        RELEASE='20.04'
    }
    stages {
        stage('Build') {
            agent any
            environment {
                LOG_LEVEL='INFO'
            }
            steps {
                echo "Hello World!!! This is the ${RELEASE} and its log level is ${LOG_LEVEL}"
            }
        }
            
            stage('Test'){
                    parallel {
                        stage('Linux') {
                            steps {
                                echo "Tests are executing tests on ${STAGE_NAME}"
                            }
                        }
                        stage('windows') {
                            steps {
                                echo "Tests are executing tests on ${STAGE_NAME}"
                            }
                        }
                    }
}    
    }
        stage('Deploy'){
            input {
              message 'wanna deploy to environement??'
              parameters {
              choice choices: ['dev', 'preprod', 'prod'], description: 'Ok . please choose one enviorment of given 3 to deploy app', name: 'environment'
             }
          }

            steps {
                echo "${RELEASE} is deployed to ${environment}"
            }
            
        }
}
   post {
  success {
      echo "${BUILD_NUMBER} is success"
  }
  failure {
    echo "${BUILD_NUMBER} is failed"
  }
}


}
